---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: raresraf/login:20200218182726
          #         env:
          #  - name: WERKZEUG_DEBUG_PIN
          #    value: "off"
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31001
  selector:
    app: login
  clusterIP: 10.96.0.3
  type: NodePort
