version: "3.3"

# docker stack deploy -c docker_config/docker-compose.yaml rafMetrics
services:
  # docker build -f mysql_config/Dockerfile -t raresraf/rafmetricsmysql:latest .
  mysql:
    image: raresraf/rafmetricsmysql:latest
    environment:
      DOCKER_COMPOSE_BUILD: "true"
    ports:
      - "3306:3306"
    # expose:
    #  - '3306'
    networks:
      - backend
    volumes:
      - db-volume:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # docker build -f WebMonitoring/DockerfileResource -t raresraf/resourcemonitor:latest .
  resourcemonitor:
    image: raresraf/resourcemonitor:latest
    depends_on:
      - mysql
    environment:
      DOCKER_COMPOSE_BUILD: "true"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

  # docker build -f WebMonitoring/DockerfileWebsite -t raresraf/websitemonitor:latest .
  websitemonitor:
    image: raresraf/websitemonitor:latest
    depends_on:
      - mysql
    environment:
      DOCKER_COMPOSE_BUILD: "true"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

  login:
    image: raresraf/login:latest
    depends_on:
      - mysql
    environment:
      DOCKER_COMPOSE_BUILD: "true"
    ports:
      - "31001:5000"
    networks:
      - backend
      - frontend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

  webmonitoringapi:
    image: raresraf/webmonitoringapi:latest
    depends_on:
      - mysql
    environment:
      DOCKER_COMPOSE_BUILD: "true"
    ports:
      - "31002:5000"
    networks:
      - backend
      - frontend
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]

  # docker build -f metricsUI/Dockerfile -t raresraf/metricsui:latest .
  metricsui:
    image: raresraf/metricsui:latest
    depends_on:
      - webmonitoringapi
      - login
    environment:
      DOCKER_COMPOSE_BUILD: "true"
    ports:
      - "31000:80"
    networks:
      - frontend
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "32001:3000"
    depends_on:
      - mysql
    environment:
      - "GF_SECURITY_ADMIN_USER=TestUsername"
      - "GF_SECURITY_ADMIN_PASSWORD=TestUsername"
    user: "0"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

volumes:
  db-volume:

networks:
  backend:
  frontend:
