version: '3.3'

# docker stack deploy -c docker_config/docker-compose.yaml rafMetrics
services:
  # docker build -f mysql_config/Dockerfile -t raresraf/rafmetricsmysql:latest .
  mysql:
    image: raresraf/rafmetricsmysql:latest
    environment:
      DOCKER_COMPOSE_BUILD: 'true'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - backend
    volumes:
      - db-volume:/var/lib/mysql

  # docker build -f WebMonitoring/DockerfileResource -t raresraf/resourcemonitor:latest .
  resourcemonitor:
    image: raresraf/resourcemonitor:latest
    depends_on:
      - mysql
    environment:
      DOCKER_COMPOSE_BUILD: 'true'
    networks:
      - backend

  # docker build -f WebMonitoring/DockerfileWebsite -t raresraf/websitemonitor:latest .
  websitemonitor:
    image: raresraf/websitemonitor:latest
    depends_on:
      - mysql
    environment:
      DOCKER_COMPOSE_BUILD: 'true'
    networks:
      - backend


volumes:
  db-volume:


networks:
  backend: