---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmonitoringapi-deployment
  labels:
    app: webmonitoringapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmonitoringapi
  template:
    metadata:
      labels:
        app: webmonitoringapi
    spec:
      containers:
        - name: webmonitoringapi
          image: raresraf/webmonitoringapi
          #         env:
          #  - name: WERKZEUG_DEBUG_PIN
          #    value: "off"
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: webmonitoringapi
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31002
  selector:
    app: webmonitoringapi
  clusterIP: 10.96.0.4
  type: NodePort
