kind: Deployment
apiVersion: apps/v1
metadata:
  name: metricsui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricsui
  template:
    metadata:
      labels:
        app: metricsui
    spec:
      containers:
        - name: metricsui
          image: raresraf/metricsui:20191114140102
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: metricsui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: metricsui
