import pymysql
from flask import jsonify
from flask import flash, request
from werkzeug import generate_password_hash, check_password_hash

from flaskext.mysql import MySQL
import os

from flask import Flask
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

mysql = MySQL()

# MySQL configurations
app.config['MYSQL_DATABASE_USER'] = 'root'
app.config['MYSQL_DATABASE_PASSWORD'] = 'password'
app.config['MYSQL_DATABASE_DB'] = 'WebMonitoring'
app.config['MYSQL_DATABASE_HOST'] = '10.96.0.2'
mysql.init_app(app)


@app.route('/')
def index():
    return "Hello, world!"


@app.route('/availableResources/<username>')
def available_resources(username):
    try:
        conn = mysql.connect()
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        cursor.execute(
            "select r.Resourceid id, r.ResourceName name, r.Command command, r.FirstAdded firstadded, resource_get_availability(r.Resourceid) status from RESOURCE r, USERS u where u.Userid = r.Userid AND u.Username='%s'"
            % (username))
        rows = cursor.fetchall()

        resp = []
        count_id = 0
        for row in rows:
            resp.append(row)
            resp[-1]['id'] = count_id
            count_id = count_id + 1

        resp = jsonify(rows)
        resp.status_code = 200
        return resp
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()


# Less than implementation with None < Anything
def lt_w_none(val1, val2):
    if val1 == None:
        return True
    if val2 == None:
        return True
    return val1 > val2


@app.route('/request_time/<resource_name>')
def request_time(resource_name):
    try:
        conn = mysql.connect()
        cursor = conn.cursor()
        """
        Compatibility warning: PEP-249 specifies that any modified
        parameters must be returned. This is currently impossible
        as they are only available by storing them in a server
        variable and then retrieved by a query. Since stored
        procedures return zero or more result sets, there is no
        reliable way to get at OUT or INOUT parameters via callproc.
        The server variables are named @_procname_n, where procname
        is the parameter above and n is the position of the parameter
        (from zero). Once all result sets generated by the procedure
        have been fetched, you can issue a SELECT @_procname_0, ...
        query using .execute() to get any OUT or INOUT values.
        """
        args = [resource_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

        cursor.callproc('resource_get_time', args)
        cursor.execute("SELECT @_resource_get_time_0, "
                       "@_resource_get_time_1, "
                       "@_resource_get_time_2, "
                       "@_resource_get_time_3, "
                       "@_resource_get_time_4, "
                       "@_resource_get_time_5, "
                       "@_resource_get_time_6, "
                       "@_resource_get_time_7, "
                       "@_resource_get_time_8, "
                       "@_resource_get_time_9, "
                       "@_resource_get_time_10, "
                       "@_resource_get_time_11, "
                       "@_resource_get_time_12 ")
        result_args = cursor.fetchone()

        cursor.callproc('resource_get_old_time', args)
        cursor.execute("SELECT @_resource_get_old_time_0, "
                       "@_resource_get_old_time_1, "
                       "@_resource_get_old_time_2, "
                       "@_resource_get_old_time_3, "
                       "@_resource_get_old_time_4, "
                       "@_resource_get_old_time_5, "
                       "@_resource_get_old_time_6, "
                       "@_resource_get_old_time_7, "
                       "@_resource_get_old_time_8, "
                       "@_resource_get_old_time_9, "
                       "@_resource_get_old_time_10, "
                       "@_resource_get_old_time_11, "
                       "@_resource_get_old_time_12 ")
        result_args_old = cursor.fetchone()

        resp = jsonify({
            "product": "Response size",
            "total": {
                "monthly": result_args[3],
                "weekly": result_args[2],
                "daily": result_args[1],
                "percent": {
                    "value": 0.2,
                    "profit": lt_w_none(result_args_old[2], result_args[2])
                }
            },
            "color": "warning",
            "lowest": {
                "monthly": {
                    "value": result_args[6],
                    "profit": lt_w_none(result_args_old[6], result_args[6])
                },
                "weekly": {
                    "value": result_args[5],
                    "profit": lt_w_none(result_args_old[5], result_args[5])
                },
                "daily": {
                    "value": result_args[4],
                    "profit": lt_w_none(result_args_old[4], result_args[4])
                }
            },
            "median": {
                "monthly": {
                    "value": result_args[9],
                    "profit": lt_w_none(result_args_old[9], result_args[9])
                },
                "weekly": {
                    "value": result_args[8],
                    "profit": lt_w_none(result_args_old[8], result_args[8])
                },
                "daily": {
                    "value": result_args[7],
                    "profit": lt_w_none(result_args_old[7], result_args[7])
                }
            },
            "highest": {
                "monthly": {
                    "value": result_args[12],
                    "profit": lt_w_none(result_args_old[12], result_args[12])
                },
                "weekly": {
                    "value": result_args[11],
                    "profit": lt_w_none(result_args_old[11], result_args[11])
                },
                "daily": {
                    "value": result_args[10],
                    "profit": lt_w_none(result_args_old[10], result_args[10])
                }
            },
            "sample": [1, 2, 3, 4, 5, 6, 7]
        })
        resp.status_code = 200
        return resp
    except Exception as e:
        print(e)
    finally:
        cursor.close()
        conn.close()


@app.errorhandler(404)
def not_found(error=None):
    message = {
        'status': 404,
        'message': 'Not Found: ' + request.url,
    }
    resp = jsonify(message)
    resp.status_code = 404

    return resp


if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)
